# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: agenda.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'agenda.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x61genda.proto\x12\tagenda.v1\"H\n\x1b\x43onsultarVeterinarioRequest\x12\x16\n\x0eid_veterinario\x18\x01 \x01(\x05\x12\x11\n\tid_bloque\x18\x02 \x01(\x05\"\x90\x01\n\x13VeterinarioResponse\x12\x16\n\x0eid_veterinario\x18\x01 \x01(\x05\x12\x0e\n\x06nombre\x18\x02 \x01(\t\x12\x14\n\x0c\x65specialidad\x18\x03 \x01(\t\x12\x11\n\tid_bloque\x18\x04 \x01(\x05\x12\x14\n\x0c\x63upos_libres\x18\x05 \x01(\x05\x12\x12\n\ndisponible\x18\x06 \x01(\x08\"=\n\x14ListarBloquesRequest\x12\x16\n\x0eid_veterinario\x18\x01 \x01(\x05\x12\r\n\x05\x66\x65\x63ha\x18\x02 \x01(\t\"\xb1\x01\n\rBloqueHorario\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x16\n\x0eid_veterinario\x18\x02 \x01(\x05\x12\x1a\n\x12nombre_veterinario\x18\x03 \x01(\t\x12\x14\n\x0c\x65specialidad\x18\x04 \x01(\t\x12\r\n\x05\x66\x65\x63ha\x18\x05 \x01(\t\x12\x13\n\x0bhora_inicio\x18\x06 \x01(\t\x12\x10\n\x08hora_fin\x18\x07 \x01(\t\x12\x14\n\x0c\x63upos_libres\x18\x08 \x01(\x05\"B\n\x15ListarBloquesResponse\x12)\n\x07\x62loques\x18\x01 \x03(\x0b\x32\x18.agenda.v1.BloqueHorario\"(\n\x13ReservarCupoRequest\x12\x11\n\tid_bloque\x18\x01 \x01(\x05\"`\n\x14ReservarCupoResponse\x12\r\n\x05\x65xito\x18\x01 \x01(\x08\x12\x0f\n\x07mensaje\x18\x02 \x01(\t\x12(\n\x06\x62loque\x18\x03 \x01(\x0b\x32\x18.agenda.v1.BloqueHorario\"\'\n\x12LiberarCupoRequest\x12\x11\n\tid_bloque\x18\x01 \x01(\x05\"5\n\x13LiberarCupoResponse\x12\r\n\x05\x65xito\x18\x01 \x01(\x08\x12\x0f\n\x07mensaje\x18\x02 \x01(\t2\xe2\x02\n\rAgendaService\x12^\n\x14\x43onsultarVeterinario\x12&.agenda.v1.ConsultarVeterinarioRequest\x1a\x1e.agenda.v1.VeterinarioResponse\x12R\n\rListarBloques\x12\x1f.agenda.v1.ListarBloquesRequest\x1a .agenda.v1.ListarBloquesResponse\x12O\n\x0cReservarCupo\x12\x1e.agenda.v1.ReservarCupoRequest\x1a\x1f.agenda.v1.ReservarCupoResponse\x12L\n\x0bLiberarCupo\x12\x1d.agenda.v1.LiberarCupoRequest\x1a\x1e.agenda.v1.LiberarCupoResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'agenda_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CONSULTARVETERINARIOREQUEST']._serialized_start=27
  _globals['_CONSULTARVETERINARIOREQUEST']._serialized_end=99
  _globals['_VETERINARIORESPONSE']._serialized_start=102
  _globals['_VETERINARIORESPONSE']._serialized_end=246
  _globals['_LISTARBLOQUESREQUEST']._serialized_start=248
  _globals['_LISTARBLOQUESREQUEST']._serialized_end=309
  _globals['_BLOQUEHORARIO']._serialized_start=312
  _globals['_BLOQUEHORARIO']._serialized_end=489
  _globals['_LISTARBLOQUESRESPONSE']._serialized_start=491
  _globals['_LISTARBLOQUESRESPONSE']._serialized_end=557
  _globals['_RESERVARCUPOREQUEST']._serialized_start=559
  _globals['_RESERVARCUPOREQUEST']._serialized_end=599
  _globals['_RESERVARCUPORESPONSE']._serialized_start=601
  _globals['_RESERVARCUPORESPONSE']._serialized_end=697
  _globals['_LIBERARCUPOREQUEST']._serialized_start=699
  _globals['_LIBERARCUPOREQUEST']._serialized_end=738
  _globals['_LIBERARCUPORESPONSE']._serialized_start=740
  _globals['_LIBERARCUPORESPONSE']._serialized_end=793
  _globals['_AGENDASERVICE']._serialized_start=796
  _globals['_AGENDASERVICE']._serialized_end=1150
# @@protoc_insertion_point(module_scope)
