# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: agenda.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'agenda.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x61genda.proto\x12\tagenda.v1\"3\n\x1e\x43onsultarDisponibilidadRequest\x12\x11\n\tid_bloque\x18\x01 \x01(\t\"Z\n\x16\x44isponibilidadResponse\x12\x11\n\tid_bloque\x18\x01 \x01(\t\x12\x19\n\x11\x63upos_disponibles\x18\x02 \x01(\x05\x12\x12\n\ndisponible\x18\x03 \x01(\x08\"=\n\x14ListarBloquesRequest\x12\x16\n\x0eid_veterinario\x18\x01 \x01(\t\x12\r\n\x05\x66\x65\x63ha\x18\x02 \x01(\t\"B\n\x15ListarBloquesResponse\x12)\n\x07\x62loques\x18\x01 \x03(\x0b\x32\x18.agenda.v1.BloqueHorario\"\xa0\x01\n\rBloqueHorario\x12\n\n\x02id\x18\x01 \x01(\t\x12\x16\n\x0eid_veterinario\x18\x02 \x01(\t\x12\x1a\n\x12nombre_veterinario\x18\x03 \x01(\t\x12\r\n\x05\x66\x65\x63ha\x18\x04 \x01(\t\x12\x13\n\x0bhora_inicio\x18\x05 \x01(\t\x12\x10\n\x08hora_fin\x18\x06 \x01(\t\x12\x19\n\x11\x63upos_disponibles\x18\x07 \x01(\x05\"(\n\x13ReservarCupoRequest\x12\x11\n\tid_bloque\x18\x01 \x01(\t\"6\n\x14ReservarCupoResponse\x12\r\n\x05\x65xito\x18\x01 \x01(\x08\x12\x0f\n\x07mensaje\x18\x02 \x01(\t\"\'\n\x12LiberarCupoRequest\x12\x11\n\tid_bloque\x18\x01 \x01(\t\"5\n\x13LiberarCupoResponse\x12\r\n\x05\x65xito\x18\x01 \x01(\x08\x12\x0f\n\x07mensaje\x18\x02 \x01(\t2\xeb\x02\n\rAgendaService\x12g\n\x17\x43onsultarDisponibilidad\x12).agenda.v1.ConsultarDisponibilidadRequest\x1a!.agenda.v1.DisponibilidadResponse\x12R\n\rListarBloques\x12\x1f.agenda.v1.ListarBloquesRequest\x1a .agenda.v1.ListarBloquesResponse\x12O\n\x0cReservarCupo\x12\x1e.agenda.v1.ReservarCupoRequest\x1a\x1f.agenda.v1.ReservarCupoResponse\x12L\n\x0bLiberarCupo\x12\x1d.agenda.v1.LiberarCupoRequest\x1a\x1e.agenda.v1.LiberarCupoResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'agenda_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CONSULTARDISPONIBILIDADREQUEST']._serialized_start=27
  _globals['_CONSULTARDISPONIBILIDADREQUEST']._serialized_end=78
  _globals['_DISPONIBILIDADRESPONSE']._serialized_start=80
  _globals['_DISPONIBILIDADRESPONSE']._serialized_end=170
  _globals['_LISTARBLOQUESREQUEST']._serialized_start=172
  _globals['_LISTARBLOQUESREQUEST']._serialized_end=233
  _globals['_LISTARBLOQUESRESPONSE']._serialized_start=235
  _globals['_LISTARBLOQUESRESPONSE']._serialized_end=301
  _globals['_BLOQUEHORARIO']._serialized_start=304
  _globals['_BLOQUEHORARIO']._serialized_end=464
  _globals['_RESERVARCUPOREQUEST']._serialized_start=466
  _globals['_RESERVARCUPOREQUEST']._serialized_end=506
  _globals['_RESERVARCUPORESPONSE']._serialized_start=508
  _globals['_RESERVARCUPORESPONSE']._serialized_end=562
  _globals['_LIBERARCUPOREQUEST']._serialized_start=564
  _globals['_LIBERARCUPOREQUEST']._serialized_end=603
  _globals['_LIBERARCUPORESPONSE']._serialized_start=605
  _globals['_LIBERARCUPORESPONSE']._serialized_end=658
  _globals['_AGENDASERVICE']._serialized_start=661
  _globals['_AGENDASERVICE']._serialized_end=1024
# @@protoc_insertion_point(module_scope)
