# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import agenda_pb2 as agenda__pb2

GRPC_GENERATED_VERSION = '1.84.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in agenda_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AgendaServiceStub:
    """Servicio que administra los veterinarios y sus bloques horarios.
    Todas las operaciones son de tipo Unary: el cliente envía un
    mensaje y recibe una única respuesta.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ConsultarVeterinario = channel.unary_unary(
                '/agenda.v1.AgendaService/ConsultarVeterinario',
                request_serializer=agenda__pb2.ConsultarVeterinarioRequest.SerializeToString,
                response_deserializer=agenda__pb2.VeterinarioResponse.FromString,
                _registered_method=True)
        self.ListarBloques = channel.unary_unary(
                '/agenda.v1.AgendaService/ListarBloques',
                request_serializer=agenda__pb2.ListarBloquesRequest.SerializeToString,
                response_deserializer=agenda__pb2.ListarBloquesResponse.FromString,
                _registered_method=True)
        self.ReservarCupo = channel.unary_unary(
                '/agenda.v1.AgendaService/ReservarCupo',
                request_serializer=agenda__pb2.ReservarCupoRequest.SerializeToString,
                response_deserializer=agenda__pb2.ReservarCupoResponse.FromString,
                _registered_method=True)
        self.LiberarCupo = channel.unary_unary(
                '/agenda.v1.AgendaService/LiberarCupo',
                request_serializer=agenda__pb2.LiberarCupoRequest.SerializeToString,
                response_deserializer=agenda__pb2.LiberarCupoResponse.FromString,
                _registered_method=True)


class AgendaServiceServicer:
    """Servicio que administra los veterinarios y sus bloques horarios.
    Todas las operaciones son de tipo Unary: el cliente envía un
    mensaje y recibe una única respuesta.
    """

    def ConsultarVeterinario(self, request, context):
        """Consulta un veterinario y los cupos libres de uno de sus bloques.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListarBloques(self, request, context):
        """Lista los bloques horarios disponibles, con filtros opcionales.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReservarCupo(self, request, context):
        """Decrementa en 1 el cupo libre de un bloque (reservar).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LiberarCupo(self, request, context):
        """Incrementa en 1 el cupo libre de un bloque (liberar al cancelar).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AgendaServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ConsultarVeterinario': grpc.unary_unary_rpc_method_handler(
                    servicer.ConsultarVeterinario,
                    request_deserializer=agenda__pb2.ConsultarVeterinarioRequest.FromString,
                    response_serializer=agenda__pb2.VeterinarioResponse.SerializeToString,
            ),
            'ListarBloques': grpc.unary_unary_rpc_method_handler(
                    servicer.ListarBloques,
                    request_deserializer=agenda__pb2.ListarBloquesRequest.FromString,
                    response_serializer=agenda__pb2.ListarBloquesResponse.SerializeToString,
            ),
            'ReservarCupo': grpc.unary_unary_rpc_method_handler(
                    servicer.ReservarCupo,
                    request_deserializer=agenda__pb2.ReservarCupoRequest.FromString,
                    response_serializer=agenda__pb2.ReservarCupoResponse.SerializeToString,
            ),
            'LiberarCupo': grpc.unary_unary_rpc_method_handler(
                    servicer.LiberarCupo,
                    request_deserializer=agenda__pb2.LiberarCupoRequest.FromString,
                    response_serializer=agenda__pb2.LiberarCupoResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'agenda.v1.AgendaService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('agenda.v1.AgendaService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AgendaService:
    """Servicio que administra los veterinarios y sus bloques horarios.
    Todas las operaciones son de tipo Unary: el cliente envía un
    mensaje y recibe una única respuesta.
    """

    @staticmethod
    def ConsultarVeterinario(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agenda.v1.AgendaService/ConsultarVeterinario',
            agenda__pb2.ConsultarVeterinarioRequest.SerializeToString,
            agenda__pb2.VeterinarioResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListarBloques(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agenda.v1.AgendaService/ListarBloques',
            agenda__pb2.ListarBloquesRequest.SerializeToString,
            agenda__pb2.ListarBloquesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReservarCupo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agenda.v1.AgendaService/ReservarCupo',
            agenda__pb2.ReservarCupoRequest.SerializeToString,
            agenda__pb2.ReservarCupoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LiberarCupo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agenda.v1.AgendaService/LiberarCupo',
            agenda__pb2.LiberarCupoRequest.SerializeToString,
            agenda__pb2.LiberarCupoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
